# Generated by Django 3.0.3 on 2021-09-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0009_auto_20200610_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishUser',
        ),
        migrations.RenameField(
            model_name='blogcontent11',
            old_name='story',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='blogcontent11',
            name='title',
        ),
    ]
