# Generated by Django 3.0.3 on 2021-09-17 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog1', '0010_auto_20210917_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogContent11',
            new_name='UserAddress',
        ),
    ]
